pipeline {
    agent any
    stages {
        stage('Checkout Repository') {
            steps {
                // Clone the repository to the Jenkins workspace
                checkout scm
            }
        }
        stage('Init') {
            steps {
                dir('./') { // Ensure the correct directory is used
                    withCredentials([usernamePassword(credentialsId: 'aws_user', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                        sh '''
                        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                        terraform init -reconfigure
                        '''
                    }
                }
            }
        }
        stage('Destroy') {
            steps {
                dir('./') { // Ensure the correct directory is used
                    // Manual approval prompt
                    input message: "Are you sure you want to destroy the resources?", ok: "Yes, Destroy"
                    withCredentials([usernamePassword(credentialsId: 'aws_user', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                        sh '''
                        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                        terraform destroy -auto-approve
                        '''
                    }
                }
            }
        }
    }
}

